import {
  BodyType,
  Condition,
  Drivetrain,
  FuelType,
  Transmission,
  type Vehicle,
} from "@/lib/api";
import { ExternalBlob } from "@caffeineai/object-storage";

export function makeVehicle(overrides: Partial<Vehicle> = {}): Vehicle {
  return {
    id: 1n,
    vin: "TESTVIN123456789",
    model: "Model 3",
    sellerNotes: "Clean title",
    title: "2022 Tesla Model 3 Long Range",
    featured: true,
    mileage: 18500n,
    drivetrain: Drivetrain.rwd,
    make: "Tesla",
    color: "Pearl White",
    year: 2022n,
    sellerContact: "seller@example.com",
    description: "Dual motor long range with autopilot.",
    transmission: Transmission.automatic,
    fuelType: FuelType.electric,
    price: 42900n,
    bodyType: BodyType.sedan,
    location: "San Francisco, CA",
    photos: [ExternalBlob.fromURL("https://example.com/photo1.jpg")],
    condition: Condition.used,
    ...overrides,
  };
}

export const sampleVehicles: Vehicle[] = [
  makeVehicle({
    id: 1n,
    title: "2022 Tesla Model 3 Long Range",
    make: "Tesla",
    model: "Model 3",
    price: 42900n,
    year: 2022n,
    mileage: 18500n,
    fuelType: FuelType.electric,
    bodyType: BodyType.sedan,
    condition: Condition.used,
    featured: true,
  }),
  makeVehicle({
    id: 2n,
    title: "2021 Toyota RAV4 Hybrid XLE",
    make: "Toyota",
    model: "RAV4",
    price: 34500n,
    year: 2021n,
    mileage: 32000n,
    fuelType: FuelType.hybrid,
    bodyType: BodyType.suv,
    condition: Condition.certifiedPreOwned,
    featured: true,
  }),
  makeVehicle({
    id: 3n,
    title: "2020 Ford F-150 XLT",
    make: "Ford",
    model: "F-150",
    price: 38200n,
    year: 2020n,
    mileage: 54000n,
    fuelType: FuelType.petrol,
    bodyType: BodyType.pickup,
    condition: Condition.used,
    featured: false,
  }),
  makeVehicle({
    id: 4n,
    title: "2024 BMW 330i Sedan",
    make: "BMW",
    model: "330i",
    price: 46800n,
    year: 2024n,
    mileage: 1200n,
    fuelType: FuelType.petrol,
    bodyType: BodyType.sedan,
    condition: Condition.new_,
    featured: true,
  }),
];
