/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const VehicleId = IDL.Nat;
export const Drivetrain = IDL.Variant({
  'awd' : IDL.Null,
  'fwd' : IDL.Null,
  'rwd' : IDL.Null,
  'fourWd' : IDL.Null,
});
export const Transmission = IDL.Variant({
  'automatic' : IDL.Null,
  'manual' : IDL.Null,
  'semiAutomatic' : IDL.Null,
});
export const FuelType = IDL.Variant({
  'petrol' : IDL.Null,
  'hybrid' : IDL.Null,
  'diesel' : IDL.Null,
  'plugInHybrid' : IDL.Null,
  'electric' : IDL.Null,
});
export const BodyType = IDL.Variant({
  'suv' : IDL.Null,
  'van' : IDL.Null,
  'convertible' : IDL.Null,
  'coupe' : IDL.Null,
  'sedan' : IDL.Null,
  'pickup' : IDL.Null,
  'wagon' : IDL.Null,
  'hatchback' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Condition = IDL.Variant({
  'new' : IDL.Null,
  'certifiedPreOwned' : IDL.Null,
  'used' : IDL.Null,
});
export const Vehicle = IDL.Record({
  'id' : VehicleId,
  'vin' : IDL.Text,
  'model' : IDL.Text,
  'sellerNotes' : IDL.Text,
  'title' : IDL.Text,
  'featured' : IDL.Bool,
  'mileage' : IDL.Nat,
  'drivetrain' : Drivetrain,
  'make' : IDL.Text,
  'color' : IDL.Text,
  'year' : IDL.Nat,
  'sellerContact' : IDL.Text,
  'description' : IDL.Text,
  'transmission' : Transmission,
  'fuelType' : FuelType,
  'price' : IDL.Nat,
  'bodyType' : BodyType,
  'location' : IDL.Text,
  'photos' : IDL.Vec(ExternalBlob),
  'condition' : Condition,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const SortField = IDL.Variant({
  'mileage' : IDL.Null,
  'year' : IDL.Null,
  'price' : IDL.Null,
});
export const SortOrder = IDL.Variant({ 'asc' : IDL.Null, 'desc' : IDL.Null });
export const VehicleFilter = IDL.Record({
  'make' : IDL.Opt(IDL.Text),
  'year' : IDL.Opt(IDL.Nat),
  'maxPrice' : IDL.Opt(IDL.Nat),
  'fuelType' : IDL.Opt(FuelType),
  'minPrice' : IDL.Opt(IDL.Nat),
  'bodyType' : IDL.Opt(BodyType),
  'condition' : IDL.Opt(Condition),
});
export const VehicleQuery = IDL.Record({
  'sortField' : SortField,
  'sortOrder' : SortOrder,
  'filter' : VehicleFilter,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createVehicle' : IDL.Func([Vehicle], [VehicleId], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getVehicle' : IDL.Func([VehicleId], [IDL.Opt(Vehicle)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'searchVehicles' : IDL.Func([VehicleQuery], [IDL.Vec(Vehicle)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const VehicleId = IDL.Nat;
  const Drivetrain = IDL.Variant({
    'awd' : IDL.Null,
    'fwd' : IDL.Null,
    'rwd' : IDL.Null,
    'fourWd' : IDL.Null,
  });
  const Transmission = IDL.Variant({
    'automatic' : IDL.Null,
    'manual' : IDL.Null,
    'semiAutomatic' : IDL.Null,
  });
  const FuelType = IDL.Variant({
    'petrol' : IDL.Null,
    'hybrid' : IDL.Null,
    'diesel' : IDL.Null,
    'plugInHybrid' : IDL.Null,
    'electric' : IDL.Null,
  });
  const BodyType = IDL.Variant({
    'suv' : IDL.Null,
    'van' : IDL.Null,
    'convertible' : IDL.Null,
    'coupe' : IDL.Null,
    'sedan' : IDL.Null,
    'pickup' : IDL.Null,
    'wagon' : IDL.Null,
    'hatchback' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Condition = IDL.Variant({
    'new' : IDL.Null,
    'certifiedPreOwned' : IDL.Null,
    'used' : IDL.Null,
  });
  const Vehicle = IDL.Record({
    'id' : VehicleId,
    'vin' : IDL.Text,
    'model' : IDL.Text,
    'sellerNotes' : IDL.Text,
    'title' : IDL.Text,
    'featured' : IDL.Bool,
    'mileage' : IDL.Nat,
    'drivetrain' : Drivetrain,
    'make' : IDL.Text,
    'color' : IDL.Text,
    'year' : IDL.Nat,
    'sellerContact' : IDL.Text,
    'description' : IDL.Text,
    'transmission' : Transmission,
    'fuelType' : FuelType,
    'price' : IDL.Nat,
    'bodyType' : BodyType,
    'location' : IDL.Text,
    'photos' : IDL.Vec(ExternalBlob),
    'condition' : Condition,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const SortField = IDL.Variant({
    'mileage' : IDL.Null,
    'year' : IDL.Null,
    'price' : IDL.Null,
  });
  const SortOrder = IDL.Variant({ 'asc' : IDL.Null, 'desc' : IDL.Null });
  const VehicleFilter = IDL.Record({
    'make' : IDL.Opt(IDL.Text),
    'year' : IDL.Opt(IDL.Nat),
    'maxPrice' : IDL.Opt(IDL.Nat),
    'fuelType' : IDL.Opt(FuelType),
    'minPrice' : IDL.Opt(IDL.Nat),
    'bodyType' : IDL.Opt(BodyType),
    'condition' : IDL.Opt(Condition),
  });
  const VehicleQuery = IDL.Record({
    'sortField' : SortField,
    'sortOrder' : SortOrder,
    'filter' : VehicleFilter,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createVehicle' : IDL.Func([Vehicle], [VehicleId], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getVehicle' : IDL.Func([VehicleId], [IDL.Opt(Vehicle)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'searchVehicles' : IDL.Func([VehicleQuery], [IDL.Vec(Vehicle)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };